/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myDemoApp;

public class App {

    public static boolean checkIsBetweenBounds(int[] array, Integer index, int lowerBound, int upperBound){

        if(array == null || index < 0 || index >= array.length ||lowerBound > upperBound){
            throw new IllegalArgumentException();
        }
        
        return (array[index] <= upperBound && array[index] >= lowerBound);
    }
}
