/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myDemoApp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test void testBetweenBounds() {
        int[] arr = new int[]{-5,6,3,9,11,6,100};
        assertTrue(App.checkIsBetweenBounds(arr, 0, -10, 0));
        assertTrue(App.checkIsBetweenBounds(arr, 4, 10, 15));
        assertTrue(App.checkIsBetweenBounds(arr, 2, 2, 3));
    }

    @Test void testNotBetweenBounds() {
        int[] arr = new int[]{-5,6,3,9,11,20,100};
        assertFalse(App.checkIsBetweenBounds(arr, 1, 4, 5));
        assertFalse(App.checkIsBetweenBounds(arr, 3, -1, 4));
        assertFalse(App.checkIsBetweenBounds(arr, 5, 30, 50));
    }

    @Test void throwsException_nullArray() {
        int[] arr = new int[]{};
        assertThrows(IllegalArgumentException.class, () -> {App.checkIsBetweenBounds(arr, 1, 3, 5);});
    }

    @Test void throwsException_negativeIndex() {
        int[] arr = new int[]{-1,0,3,5,9,11};
        assertThrows(IllegalArgumentException.class, () -> {App.checkIsBetweenBounds(arr, -5, 3, 5);});
    }

    @Test void throwsException_shortArraybyIndex() {
        int[] arr = new int[]{-1,0,3,5,9,11};
        assertThrows(IllegalArgumentException.class, () -> {App.checkIsBetweenBounds(arr, 10, 3, 5);});
    }

    @Test void throwsException_lowerBoundIsBiggerThanUpper() {
        int[] arr = new int[]{-1,0,3,5,9,11};
        assertThrows(IllegalArgumentException.class, () -> {App.checkIsBetweenBounds(arr, 3, 7, 4);});
    }
}
